process.on('uncaughtException', console.error) //Safe Log Error 
module.exports = {
modul: {
	axios: require('axios'),
	boom: require('@hapi/boom'),
	baileys: require('@adiwajshing/baileys'), 
	chalk: require('chalk'),
	crypto: require('crypto'),
	cheerio: require('cheerio'),
	child_process: require('child_process'),
	cookie: require('cookie'),
    fs: require('fs'),
	OpenAIApi: require("openai"),
	figlet: require('figlet'),
	FormData: require('form-data'),
	FileType: require('file-type'),
	ffmpeg: require('fluent-ffmpeg'),
	got: require('got'),
	gimage: require('g-i-s'),
	google: require('google-it'),
	human: require('human-readable'),
	Jimp: require('jimp'),
	jsdom: require('jsdom'),
	keyeddb: require('@adiwajshing/keyed-db'),
	lodash: require('lodash'),
	moment: require('moment-timezone'),
	ms: require('ms'),
	nodecron: require('node-cron'),
	os: require('os'),
	path: require('path'),
	perf_hooks: require('perf_hooks'),
	pino: require('pino'),
	process: require('process'),
	PhoneNumber: require('awesome-phonenumber'),
	qs: require('qs'),
    qrcodeterminal: require('qrcode-terminal'),
    qrcode: require('qrcode'),
    request: require('request'),
    scrapePrimbon: require('scrape-primbon'),
    speed: require('performance-now'),
    stream: require('stream'),
    util: require('util'),
    Utils: require('@adiwajshing/baileys/lib/Utils'),
    yargs: require('yargs'),
    yts: require('yt-search'),
    webp: require('node-webpmux')
}
}